### ISSUE TITLE
Want to use in my existing ionic 3 project ,but not working .

### ISSUE THREAD

**Issue by Anujmoglix** [anggaand123/Ionic-3-Material-Design#2]
Hi ,
  I want to use material Design in my present app which is having lazy loading concept . I downloaded dependency but i am not able to use it . What process should i use for working this ?
i am getting this 
**TypeError: Object(...) is not a function**

**Comment by whatnowangga** [comment]
just copy dependencies in package.json

**Comment by Anujmoglix** [comment]
Hi ,
   i put all in my package json which looks like this now : 

```
    "@angular/animations": "^5.2.1",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "5.0.3",
    "@angular/compiler": "5.0.3",
    "@angular/compiler-cli": "5.0.3",
    "@angular/core": "5.0.3",
    "@angular/forms": "5.0.3",
    "@angular/http": "5.0.3",
    "@angular/material": "github:angular/material2-builds",
    "@angular/platform-browser": "5.0.3",
    "@angular/platform-browser-dynamic": "5.0.3",
```

then i did **npm install** .It install all package but getting issues

**Comment by whatnowangga** [comment]
what issue ?

**Comment by Anujmoglix** [comment]
In your repo when i am trying to do lazy loading then i am getting 

> Uncaught (in promise): Error: No ErrorHandler. Is platform module (BrowserModule) included?
> Error: No ErrorHandler. Is platform module (BrowserModule) included?

when i am doing 

> npm install ts-md5 --save

for installing other npm then getting **Cannot find module '@angular/material'.**

Am i doing something wrong ?

**Comment by whatnowangga** [comment]
that is something problem with your code/plugin not my template

**Comment by Anujmoglix** [comment]
some more errors i am getting 
![image](https://user-images.githubusercontent.com/26056096/40711249-539071ee-6418-11e8-82e2-c34a86324d88.png)

**Comment by whatnowangga** [comment]
please share your ionic info
